### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by qrpike** [xdsopl/framebuffer#1]
The library works great, however im curious if there are ways to improve the rendering speed.  I'm getting like 3fps. It's a armv5 machine

Thanks,

**Comment by xdsopl** [comment]
If you have different format source / destination frame buffers, then Golang's draw.Draw() falls back to the slower path and uses the image.Image and the color.Color interface at each pixel, which is unfortunately the price one has to pay to gain flexibility at reduced code complexity.

Ahmet

**Comment by qrpike** [comment]
Can you elaborate on the source/destination? You mean like image format types?

What would be the correct source type to have it render at a decent speed? I can literally watch it draw each line on the screen ;p 

Thanks for your work, I'm really hoping to use it!

**Comment by xdsopl** [comment]
I meant the src / dst [image.Image](https://golang.org/pkg/image/draw/#Image) arguments to the [draw.Draw()](https://golang.org/pkg/image/draw/#Draw) function.

I guess you're trying to show a GIF animation where each src frame from the decoded GIF is copied to the dst frame, one after another, correct?

So if you have enough system memory, you could render the entire GIF animation to frame buffers of the same type, that you got from framebuffer.Open().

Then you could basically use the builtin [copy](https://golang.org/pkg/builtin/#copy) function and be done here.

Another option is, if you have a lot of video memory and even can change the displayed resolution to a lower one while having a bigger virtual resolution, to render all GIF frames to the video frame buffer side by side and if supported by the video driver, simply call the FBIOPAN_DISPLAY ioctl to switch the output between the frames.

Panning is usually instantaneous and if implemented correctly, done at the vertical retrace and therefore you would have a very smooth animation.

I really do love Golang, but for this kind of thing, where I need the highest performance while keeping the flexibility, I always return back to C++ and template code.

I will give it some time and thought if I can improve things, but I can give no promises ;-)

Ahmet
